const SET_INFO = "SET_INFO";
const REMOVE_INFO = "REMOVE_INFO";
const SET_ROLE = "SET_ROLE";
const REMOVE_ROLE = "REMOVE_ROLE";
const SET_USER = "SET_USER";
const REMOVE_USER = "REMOVE_USER";
const SET_DOCTOR = "SET_DOCTOR";
const REMOVE_DOCTOR = "REMOVE_DOCTOR";

export {
  SET_INFO,
  REMOVE_INFO,
  SET_ROLE,
  REMOVE_ROLE,
  SET_USER,
  REMOVE_USER,
  SET_DOCTOR,
  REMOVE_DOCTOR,
};
